global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'doctor-clinic-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'Doctors-Clinic-DevOps-System'

  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']