apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-clinic-app
  namespace: doctor-clinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-clinic-app
  template:
    metadata:
      labels:
        app: doctor-clinic-app
    spec:
      containers:
        - name: app
          image: doctors-clinic-system-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: doctor-clinic-secret
