apiVersion: v1
kind: Secret
metadata:
  name: doctor-clinic-secret
  namespace: doctor-clinic
type: Opaque
stringData:
  APP_NAME: "Doctor Clinic DevOps System"
  APP_ENV: "production"
  APP_KEY: "base64:CHANGE_ME_LATER"
  APP_DEBUG: "false"
  APP_URL: "http://localhost"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "doktors"
  DB_USERNAME: "doktors_user"
  DB_PASSWORD: "doktors_pass"
